languageCode = "en-us"
title = "The latest in technology, computing and engineering"
copyright = ""
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true
paginate = 5
disableKinds = [ "taxonomyTerm" ]
ignoreErrors = ["error-remote-getjson"]
pygmentsCodeFences = true
pygmentsStyle = "monokai"
[taxonomies]
   tag = "tags"
   category = "categories"
   topic = "topics"
   author = "authors"
[permalinks]
   guruspedia = "/:slug/"
   articles = "/:slug/"
   topics = "/topic/:slug/"
   tags = "/tag/:slug/"
[author]
  name = "Guru Spedia"
  email = "guruspedia@gmail.com"
[params]
  dateformat = "January 2, 2006"
  description = "The latest in technology, computing and engineering."
[markup.goldmark.renderer]
  unsafe = true
[social]
email = "guruspedia@gmail.com"
linkedin = "https://www.linkedin.com/in/gurus-pedia-83b777287/"
twitter = "https://twitter/GurusPedia"
github = "https://github.com/kimkimani/"
[blackfriday]
  plainIDAnchors = true
[related]
threshold = 80
includeNewer = true
toLower = false
[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "tags"
weight = 80
[[related.indices]]
name  = "categories"
weight = 80
[[related.indices]]
name  = "topics"
weight = 80
[[related.indices]]
name  = "date"
weight = 10

[params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info:"
      address = "GurusPedia"
      phone   = "Email Address"
      email   = "guruspedia@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap:"
        [[params.footer.sitemap.link]]
          name = "About GurusPedia"
          url  = "/about"
        [[params.footer.sitemap.link]]
          name = "Write With Us"
          url  = "/"
        [[params.footer.sitemap.link]]
          name = "Instructors"
          url  = "/authors"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "/contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Socials:"
        [[params.footer.social.link]]
          name = "Twiter"
          url  = "https://twitter.com/GurusPedia"
        [[params.footer.social.link]]
          name = "Linkedin"
          url  = "https://www.linkedin.com/in/gurus-pedia-83b777287/"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "/contact"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "/contact"
      # Footer Service
      [params.footer.service]
        title       = "GurusPedia Quest:"
        description = "Tech Exploration and Enlightenment.<br>Unleashing the Digital Curiosity<br>with Shared Brilliance One<br>Byte at a Time"